meta_product_name: "Cheers"
meta_title: "Cheers, accords mets et vins"
meta_description: "Cheers, votre sommelier digital qui allie vos mets à des vins d'exception"
meta_image: "logo.png" # should exist in `app/assets/images/`
